const express = require('express');
const rateLimit = require('express-rate-limit');
const path = require('path');
const fs = require('fs');
const fsp = require('fs/promises');
const { spawn } = require('child_process');
const crypto = require('crypto');

const app = express();
const PORT = process.env.PORT || 3000;
const DOWNLOAD_DIR = path.join(__dirname, 'downloads');
const PUBLIC_DIR = path.join(__dirname, 'public');
const MAX_FILE_AGE_MS = Number(process.env.MAX_FILE_AGE_MS || 60 * 60 * 1000);
const YTDLP_BIN = process.env.YTDLP_BIN || 'yt-dlp';

const DOWNLOAD_TYPES = new Map([
  ['video-only', {
    extension: '.mp4',
    label: 'video only',
    args: commonArgs => [
      ...commonArgs,
      '-f', 'bv*[ext=mp4]/bestvideo[ext=mp4]/bv*/bestvideo',
      '--merge-output-format', 'mp4'
    ]
  }],
  ['audio', {
    extension: '.mp3',
    label: 'voice only',
    args: commonArgs => [
      ...commonArgs,
      '-x',
      '--audio-format', 'mp3',
      '--audio-quality', '0'
    ]
  }],
  ['video-audio', {
    extension: '.mp4',
    label: 'video with voice',
    args: commonArgs => [
      ...commonArgs,
      '-f', 'bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4]/best',
      '--merge-output-format', 'mp4'
    ]
  }]
]);

fs.mkdirSync(DOWNLOAD_DIR, { recursive: true });

app.use(express.json({ limit: '16kb' }));
app.use(express.static(PUBLIC_DIR));
app.use('/downloads', express.static(DOWNLOAD_DIR, {
  fallthrough: false,
  setHeaders(res) {
    res.setHeader('Content-Disposition', 'attachment');
    res.setHeader('X-Content-Type-Options', 'nosniff');
  }
}));

// Keep a small public demo from being hammered with expensive media jobs.
const downloadLimiter = rateLimit({
  windowMs: 15 * 60 * 1000,
  limit: 8,
  standardHeaders: true,
  legacyHeaders: false,
  message: {
    success: false,
    error: 'Too many download requests. Please wait a bit and try again.'
  }
});

function isAllowedYouTubeUrl(value) {
  try {
    const parsed = new URL(value);
    const host = parsed.hostname.toLowerCase().replace(/^www\./, '');
    return parsed.protocol === 'https:' && (host === 'youtube.com' || host === 'm.youtube.com' || host === 'youtu.be');
  } catch {
    return false;
  }
}

function normalizeDownloadType(type) {
  // Backward compatibility: the original API used "video" for video plus audio.
  if (type === 'video') return 'video-audio';
  return type;
}

// File names are generated by the server and restricted to portable characters.
function sanitizeFilePart(value) {
  return String(value)
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-zA-Z0-9._-]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 80) || 'download';
}

function runYtDlp(args) {
  return new Promise((resolve, reject) => {
    let stderr = '';

    // Use spawn with an argument array so user input never becomes a raw shell command.
    const child = spawn(YTDLP_BIN, args, {
      cwd: __dirname,
      windowsHide: true,
      shell: false
    });

    child.stderr.on('data', chunk => {
      stderr += chunk.toString();
    });

    child.on('error', error => {
      reject(new Error(`Could not start yt-dlp. Make sure it is installed and on PATH. ${error.message}`));
    });

    child.on('close', code => {
      if (code === 0) {
        resolve();
        return;
      }

      const cleanError = stderr.split('\n').slice(-8).join('\n').trim();
      reject(new Error(cleanError || `yt-dlp exited with code ${code}`));
    });
  });
}

async function findNewestFile(prefix, extension) {
  const files = await fsp.readdir(DOWNLOAD_DIR, { withFileTypes: true });
  const matches = [];

  for (const file of files) {
    if (!file.isFile() || !file.name.startsWith(prefix) || !file.name.endsWith(extension)) {
      continue;
    }
    const fullPath = path.join(DOWNLOAD_DIR, file.name);
    const stat = await fsp.stat(fullPath);
    matches.push({ name: file.name, mtimeMs: stat.mtimeMs });
  }

  matches.sort((a, b) => b.mtimeMs - a.mtimeMs);
  return matches[0]?.name;
}

async function cleanupOldDownloads() {
  const now = Date.now();
  const files = await fsp.readdir(DOWNLOAD_DIR, { withFileTypes: true });

  await Promise.all(files.map(async file => {
    if (!file.isFile()) return;
    const filePath = path.join(DOWNLOAD_DIR, file.name);
    const stat = await fsp.stat(filePath);
    if (now - stat.mtimeMs > MAX_FILE_AGE_MS) {
      await fsp.unlink(filePath).catch(() => {});
    }
  }));
}

// Run cleanup in the background and also before each new job.
setInterval(() => {
  cleanupOldDownloads().catch(error => console.error('Download cleanup failed:', error.message));
}, 10 * 60 * 1000).unref();

app.post('/api/download', downloadLimiter, async (req, res) => {
  const { url } = req.body || {};
  const type = normalizeDownloadType(req.body?.type);
  const downloadType = DOWNLOAD_TYPES.get(type);

  if (!url || typeof url !== 'string' || !url.trim()) {
    return res.status(400).json({ success: false, error: 'Please paste a YouTube URL.' });
  }

  if (!isAllowedYouTubeUrl(url.trim())) {
    return res.status(400).json({ success: false, error: 'Only public youtube.com and youtu.be HTTPS URLs are allowed.' });
  }

  if (!downloadType) {
    return res.status(400).json({ success: false, error: 'Choose video only, voice only, or video with voice.' });
  }

  await cleanupOldDownloads().catch(() => {});

  const id = crypto.randomUUID ? crypto.randomUUID() : crypto.randomBytes(16).toString('hex');
  const prefix = sanitizeFilePart(`${type}-${id}`);
  const outputTemplate = path.join(DOWNLOAD_DIR, `${prefix}.%(ext)s`);

  const commonArgs = [
    '--no-playlist',
    '--no-cache-dir',
    '--restrict-filenames',
    '--windows-filenames',
    '--no-part',
    '-o', outputTemplate
  ];

  const args = [
    ...downloadType.args(commonArgs),
    url.trim()
  ];

  try {
    await runYtDlp(args);
    const filename = await findNewestFile(prefix, downloadType.extension);

    if (!filename) {
      return res.status(500).json({ success: false, error: 'The file was processed but could not be found.' });
    }

    return res.json({
      success: true,
      downloadUrl: `/downloads/${encodeURIComponent(filename)}`
    });
  } catch (error) {
    return res.status(500).json({
      success: false,
      error: error.message || `Could not create the ${downloadType.label} file. Please try another allowed public video.`
    });
  }
});

app.use((req, res) => {
  res.status(404).json({ success: false, error: 'Not found.' });
});

app.listen(PORT, () => {
  console.log(`Server running at http://localhost:${PORT}`);
});
